apiVersion: v1
kind: ServiceAccount
metadata:
  name: netdebug
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: netdebug
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list"]
  resourceNames: ["netdebug-config"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: netdebug
subjects:
- kind: ServiceAccount
  name: netdebug
  namespace: default
roleRef:
  kind: ClusterRole
  name: netdebug
  apiGroup: rbac.authorization.k8s.io
